import 'ventas_modelos.dart';

class VentasDatos {
  static List<ProductoVenta> productosIniciales() {
    return const [
      ProductoVenta(
        id: 1,
        nombre: 'Empanada Mozarella',
        categoria: 'Empanadas',
        precio: 1.75,
        seccion: SeccionVenta.individuales,
        requiereSabores: false,
        cantidadSabores: 0,
        controlaStock: true,
      ),
      ProductoVenta(
        id: 2,
        nombre: 'Empanada Pollo Mozarella',
        categoria: 'Empanadas',
        precio: 2.00,
        seccion: SeccionVenta.individuales,
        requiereSabores: false,
        cantidadSabores: 0,
        controlaStock: true,
      ),
      ProductoVenta(
        id: 3,
        nombre: 'Empanada Jamonera',
        categoria: 'Empanadas',
        precio: 1.90,
        seccion: SeccionVenta.individuales,
        requiereSabores: false,
        cantidadSabores: 0,
        controlaStock: true,
      ),
      ProductoVenta(
        id: 4,
        nombre: 'Empanada Hawaiana',
        categoria: 'Empanadas',
        precio: 2.10,
        seccion: SeccionVenta.individuales,
        requiereSabores: false,
        cantidadSabores: 0,
        controlaStock: true,
      ),
      ProductoVenta(
        id: 5,
        nombre: 'Coca Cola',
        categoria: 'Bebidas',
        precio: 1.00,
        seccion: SeccionVenta.individuales,
        requiereSabores: false,
        cantidadSabores: 0,
        controlaStock: true,
      ),
      ProductoVenta(
        id: 6,
        nombre: 'Chocolate',
        categoria: 'Bebidas',
        precio: 1.50,
        seccion: SeccionVenta.individuales,
        requiereSabores: false,
        cantidadSabores: 0,
        controlaStock: true,
      ),
      ProductoVenta(
        id: 7,
        nombre: 'Café',
        categoria: 'Bebidas',
        precio: 1.25,
        seccion: SeccionVenta.individuales,
        requiereSabores: false,
        cantidadSabores: 0,
        controlaStock: true,
      ),
      ProductoVenta(
        id: 8,
        nombre: 'Té',
        categoria: 'Bebidas',
        precio: 1.00,
        seccion: SeccionVenta.individuales,
        requiereSabores: false,
        cantidadSabores: 0,
        controlaStock: true,
      ),
      ProductoVenta(
        id: 9,
        nombre: 'Combo 2x1',
        categoria: 'Combos',
        precio: 3.50,
        seccion: SeccionVenta.combos,
        requiereSabores: true,
        cantidadSabores: 2,
        controlaStock: false,
      ),
      ProductoVenta(
        id: 10,
        nombre: 'Combo 12 Empanadas',
        categoria: 'Combos',
        precio: 10.99,
        seccion: SeccionVenta.combos,
        requiereSabores: true,
        cantidadSabores: 12,
        controlaStock: false,
      ),
      ProductoVenta(
        id: 11,
        nombre: 'Uber Individual Mozarella',
        categoria: 'Uber',
        precio: 2.10,
        seccion: SeccionVenta.uber,
        requiereSabores: false,
        cantidadSabores: 0,
        controlaStock: false,
      ),
      ProductoVenta(
        id: 12,
        nombre: 'Uber Combo 6 Empanadas',
        categoria: 'Uber',
        precio: 6.50,
        seccion: SeccionVenta.uber,
        requiereSabores: true,
        cantidadSabores: 6,
        controlaStock: false,
      ),
    ];
  }
}